version: "3.7"

services:
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile.local_dev
    volumes:
      - type: bind
        source: ./frontend
        target: /app
    environment:
      BACKEND_ADDR: backend:8080
    ports:
      - "3000:3000"
  backend:
    build:
      context: backend
      dockerfile: Dockerfile.local_dev
    volumes:
      - type: bind
        source: ./backend
        target: /usr/src
    environment:
      DB_HOST: postgres
    ports:
      - "8080:8080"
  postgres:
    image: postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
